import './styles.css';

type RecordItem = {
  id:string; kind:'expense'|'income'; record_date:string; description:string; amount_pence:number;
  category:string; source:'manual'|'bank'; evidence_name:string|null; invoice_number:string|null;
};
type WorkspaceResponse = {records:RecordItem[];summary:{total:number;missing:number}};
type Quarter = {label:string;from:string;to:string;year:number;q:number};

const app = document.querySelector<HTMLDivElement>('#app')!;
const routeStatus = document.querySelector<HTMLDivElement>('#route-status')!;
const DEMO_KEY = 'demo:mtd-evidence-rail:workspace';
const REAL_KEY = 'mtd-evidence-rail:workspace';
const LICENSE_KEY = 'sb_license:mtd-evidence-rail';
const LICENSE_CACHE_KEY = 'sb_license_cache:mtd-evidence-rail';
let currentRecords:RecordItem[] = [];
let currentQuarter:Quarter;
let showMissingOnly = false;
let demoMode = false;
let lastTrigger:HTMLElement|null = null;
let hasRendered = false;

function isDemoLocation(){return location.pathname==='/demo'||new URLSearchParams(location.search).get('demo')==='1';}

const escapeHtml = (value:string) => value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const money = (pence:number) => new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(pence/100);
const prettyDate = (date:string) => new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));

function icon(){return `<svg aria-hidden="true" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#092a32"/><path d="M10 44c12-2 15-17 27-17 8 0 10 7 17 7" fill="none" stroke="#e8bf62" stroke-width="5" stroke-linecap="round"/><path d="M13 49h39M18 42v12m10-18v18m10-22v22m10-22v22" stroke="#f4efe2" stroke-width="2"/><circle cx="48" cy="18" r="7" fill="#e35f3d"/></svg>`}

function header(active=''){
  return `<header class="site-header"><div class="shell header-inner"><a class="wordmark" href="/" data-route>${icon()}<span>MTD Evidence Rail</span></a><nav class="site-nav" aria-label="Main navigation"><a href="/" data-route ${active==='home'?'aria-current="page"':''}>Home</a><a href="/?demo=1" data-route ${active==='demo'?'aria-current="page"':''}>Demo</a><a href="/#price">Price</a><a href="/privacy" data-route ${active==='privacy'?'aria-current="page"':''}>Privacy</a></nav></div></header>`;
}
function footer(){return `<footer class="site-footer"><div class="shell"><div class="footer-grid"><div><a class="wordmark" href="/" data-route>${icon()}<span>MTD Evidence Rail</span></a><p>Link each expense to evidence before your quarterly update.</p></div><div class="footer-links"><a href="/privacy" data-route>Privacy</a><a href="/terms" data-route>Terms</a><a href="https://sociobot.in" rel="external">Built by Param Factory <span class="sr-only">(external site)</span></a></div></div><p class="fine">Version 1.0 · Build 2026.08 · Generated hero imagery is original to this product.</p></div></footer>`}

function landing(){
  document.title='MTD Evidence Rail — link expenses to evidence';
  app.innerHTML=`${header('home')}<main id="main">
    <section class="hero"><div class="shell hero-grid"><div class="hero-copy"><p class="eyebrow">Evidence for your MTD quarter</p><h1 tabindex="-1">Link each expense to evidence</h1><p>For sole traders who need a reviewable record before each MTD quarterly update.</p><div class="action-row"><a class="primary" href="/?demo=1" data-route>Try it with sample data</a><span class="next-note">See a ready quarter. Changes stay in this 24-hour demo.</span><a class="secondary" href="/app" data-route>Start a private workspace</a></div><ul class="facts"><li>Your workspace needs no account.</li><li>£15/month for more than 25 transactions.</li><li>Export a ZIP evidence pack.</li></ul></div><div class="hero-art"><picture><source media="(max-width:700px)" srcset="/assets/evidence-rail-hero-768.webp"><img src="/assets/evidence-rail-hero.webp" width="1280" height="853" alt="A paper train carries expense records towards a moon-shaped archive." fetchpriority="high" decoding="async"></picture><span class="train-marker" aria-hidden="true"></span></div></div></section>
    <section class="section preview" aria-labelledby="preview-title"><div class="shell"><p class="section-kicker">A quarter at a glance</p><h2 id="preview-title">See what still needs evidence</h2><p class="section-lead">Transactions, invoices, and receipts appear in one dated view. Missing evidence stays visible until you link it.</p><div class="preview-frame"><div class="rail-panel"><h3>6 Apr – 5 Jul 2026</h3><ol class="quarter-rail"><li class="active">Capture</li><li class="active">Match</li><li>Review</li><li>Export</li></ol></div><div class="mini-records"><div class="mini-records-header"><div><strong>Quarter record</strong><br><span>6 transactions</span></div><span class="status missing">2 need evidence</span></div><div class="mini-record"><time>11 Jun</time><div><strong>Teaching card supplies</strong><small>Materials · £32.99</small></div><span class="status">Evidence linked</span></div><div class="mini-record"><time>19 May</time><div><strong>Train to client session</strong><small>Travel · £27.80</small></div><span class="status missing">Evidence missing</span></div><div class="mini-record"><time>15 Apr</time><div><strong>Spring maths tutoring</strong><small>Invoice INV-026 · £120.00</small></div><span class="status">Evidence linked</span></div></div></div></div></section>
    <section class="section" aria-labelledby="how-title"><div class="shell"><p class="section-kicker">How it works</p><h2 id="how-title">Prepare the quarter while it happens</h2><div class="steps"><article class="step"><h3>Add each transaction</h3><p>Record income or expenses. You can also import a bank CSV.</p></article><article class="step"><h3>Link the evidence</h3><p>Add a receipt, invoice, or note. Likely CSV matches are flagged before import.</p></article><article class="step"><h3>Export the evidence pack</h3><p>Download one ZIP with a transaction CSV and every linked file.</p></article></div></div></section>
    <section class="section limits" aria-labelledby="limits-title"><div class="shell limits-grid"><div><p class="section-kicker">What this record tool does not do</p><h2 id="limits-title">Organise source records before your filing</h2><p>Add transactions and linked evidence. Export the pack when you are ready to file.</p></div><div><h3>Workspace privacy, export, and deletion</h3><ul><li>Workspace keys are stored on this device.</li><li>Demo records use a separate 24-hour workspace.</li><li>You can export or delete your workspace.</li><li>No advertising trackers or third-party scripts run here.</li></ul></div></div></section>
    <section class="section price" id="price" aria-labelledby="price-title"><div class="shell price-grid"><div><p class="section-kicker">Monthly subscription</p><h2 id="price-title">Use one workspace for every quarter</h2><p>The free workspace accepts 25 transactions in a quarter. A £15/month subscription accepts more than 25.</p></div><div class="price-ticket"><div class="price-number">£15 <small>per month</small></div><p>The server verifies an active subscription before accepting more than 25 transactions.</p><ul><li>Receipt and invoice evidence</li><li>Bank CSV review</li><li>Accountant evidence packs</li></ul><a class="primary" href="https://api.sociobot.in/api/v1/products/mtd-evidence-rail/checkout">Start monthly subscription</a><p class="help">Sociobot and Dodo handle subscription checkout and refunds. See the <a href="/terms" data-route>terms</a>.</p><div class="license-box"><label class="field-label" for="landing-license">Have a subscription token? Paste it here.</label><div class="license-row"><input id="landing-license" autocomplete="off" spellcheck="false"><button class="quiet" type="button" data-restore-license="landing-license">Restore subscription access</button></div><p id="license-message" class="help" aria-live="polite"></p></div></div></div></section>
  </main>${footer()}`;
  bindLicenseButtons();
  if(licenseInactive())document.querySelector<HTMLParagraphElement>('#license-message')!.textContent='Your subscription is no longer active. Free limits apply.';
}

function appBanner(){return demoMode?`<aside class="demo-banner" aria-label="Demo controls"><div class="shell"><strong>Demo — sample data. Changes stay in this 24-hour demo.</strong><button type="button" id="reset-demo">Reset demo</button><a href="/app" data-route>Start for real</a></div></aside>`:''}

function quarterFor(year:number,q:number):Quarter{
  const pad=(n:number)=>String(n).padStart(2,'0');
  const ranges=[[year,4,6,year,7,5],[year,7,6,year,10,5],[year,10,6,year+1,1,5],[year+1,1,6,year+1,4,5]][q-1];
  return {year,q,label:`Quarter ${q} · ${year}/${String(year+1).slice(-2)}`,from:`${ranges[0]}-${pad(ranges[1])}-${pad(ranges[2])}`,to:`${ranges[3]}-${pad(ranges[4])}-${pad(ranges[5])}`};
}
function quarterOptions(selected:Quarter){
  const options:Quarter[]=[]; for(let y=2025;y<=2027;y++) for(let q=1;q<=4;q++) options.push(quarterFor(y,q));
  return options.map(v=>`<option value="${v.year}-${v.q}" ${v.year===selected.year&&v.q===selected.q?'selected':''}>${v.label} · ${prettyDate(v.from)} to ${prettyDate(v.to)}</option>`).join('');
}

async function workspaceKey():Promise<string>{
  const storage=demoMode?sessionStorage:localStorage; const key=demoMode?DEMO_KEY:REAL_KEY;
  const current=storage.getItem(key); if(current) return current;
  const response=await fetch(demoMode?'/api/demo':'/api/workspace',{method:'POST'});
  if(!response.ok) throw new Error(await apiError(response));
  const data=await response.json(); storage.setItem(key,data.workspace_id); return data.workspace_id;
}
async function api(path:string,init:RequestInit={}):Promise<Response>{
  const key=await workspaceKey();
  const headers=new Headers(init.headers); headers.set('X-Workspace-Key',key); if(!demoMode){const license=localStorage.getItem(LICENSE_KEY);if(license)headers.set('X-License-Key',license);}if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');
  const response=await fetch(path,{...init,headers}); if(!response.ok)throw new Error(await apiError(response)); return response;
}
async function apiError(response:Response){try{return (await response.json()).error||`Request failed (${response.status}).`;}catch{return `Request failed (${response.status}).`;}}

async function appPage(isDemo:boolean){
  demoMode=isDemo; document.title=`${isDemo?'Demo':'Quarter'} — MTD Evidence Rail`; const now=new Date();
  const month=now.getUTCMonth()+1;const day=now.getUTCDate();let taxYear=now.getUTCFullYear();let q=1;
  if(month<4||(month===4&&day<6)){taxYear--;q=month===1&&day<6?3:4;}else if(month<7||(month===7&&day<6))q=1;else if(month<10||(month===10&&day<6))q=2;else q=3;
  currentQuarter=isDemo?quarterFor(2026,1):quarterFor(taxYear,q);
  app.innerHTML=`${header(isDemo?'demo':'')}${appBanner()}<main id="main" class="app-page"><section class="app-top"><div class="shell"><p class="eyebrow">Evidence workspace</p><h1 tabindex="-1">Prepare your quarter record</h1><p>Link every transaction to evidence, then export the quarter.</p><div class="quarter-controls"><div class="field"><label for="quarter">Quarter</label><select id="quarter">${quarterOptions(currentQuarter)}</select></div><span id="quarter-range">${prettyDate(currentQuarter.from)} to ${prettyDate(currentQuarter.to)}</span></div></div></section><section class="app-actions" aria-label="Record actions"><div class="shell action-bar"><button class="primary" type="button" id="add-record" disabled>Add a transaction</button><button class="quiet" type="button" id="import-csv" disabled>Import bank CSV</button><button class="quiet" type="button" id="missing-filter" aria-pressed="false" disabled>Show missing evidence</button><button class="quiet" type="button" id="export-pack" disabled>Export evidence pack</button><button class="quiet" type="button" id="workspace-settings" disabled>Workspace settings</button></div></section><section class="dashboard shell" aria-labelledby="records-title"><div id="app-notice" aria-live="polite"></div><div id="records-view" class="loading"><span>Loading quarter records…</span></div></section></main>${dialogs()}${footer()}`;
  bindApp(); await loadRecords(); if(licenseInactive())setNotice('Your subscription is no longer active. Free limits apply. Start a monthly subscription from the home page.');
}

function dialogs(){return `<dialog id="record-dialog" aria-labelledby="record-dialog-title"><form id="record-form"><div class="dialog-head"><h2 id="record-dialog-title">Add a transaction</h2><button class="icon-button close-dialog" type="button" aria-label="Close transaction form">×</button></div><div class="dialog-body"><div class="form-grid"><div class="field"><label for="kind">Type</label><select id="kind" name="kind"><option value="expense">Expense</option><option value="income">Income</option></select></div><div class="field"><label for="record-date">Date</label><input id="record-date" name="record_date" type="date" required></div><div class="field wide"><label for="description">Description</label><input id="description" name="description" maxlength="120" required></div><div class="field"><label for="amount">Amount in pounds</label><input id="amount" name="amount" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" required></div><div class="field"><label for="category">Category</label><input id="category" name="category" maxlength="40" required></div><div class="field wide"><label for="invoice-number">Invoice number <span class="help">(optional)</span></label><input id="invoice-number" name="invoice_number" maxlength="50"></div></div><div id="form-error" class="notice error" aria-live="assertive" hidden></div><div class="form-actions"><button type="button" class="quiet close-dialog">Cancel</button><button type="submit" class="primary">Save transaction</button></div></div></form></dialog>
  <dialog id="import-dialog" aria-labelledby="import-title"><div class="dialog-head"><h2 id="import-title">Import a bank CSV</h2><button class="icon-button close-dialog" type="button" aria-label="Close bank import">×</button></div><div class="dialog-body"><div id="import-pick"><div class="field"><label for="csv-file">Bank CSV file</label><input id="csv-file" type="file" accept=".csv,text/csv"><p class="help">Use Date, Description, and Amount columns. Negative amounts become expenses.</p></div></div><div id="import-review" aria-live="polite"></div><div class="form-actions"><button type="button" class="quiet close-dialog">Cancel</button><button type="button" class="primary" id="confirm-import" hidden>Import new transactions</button></div></div></dialog>
  <dialog id="settings-dialog" aria-labelledby="settings-title"><div class="dialog-head"><h2 id="settings-title">Workspace settings</h2><button class="icon-button close-dialog" type="button" aria-label="Close workspace settings">×</button></div><div class="dialog-body"><h3>Keep a copy</h3><p>Export each quarter before you remove this workspace.</p><button class="quiet" type="button" id="settings-export">Export this quarter</button><div class="license-box"><h3>Delete this workspace</h3><p>This removes every transaction and evidence file. This action cannot be undone.</p><button class="danger-button" type="button" id="delete-workspace">Delete all workspace data</button></div></div></dialog>`}

function bindApp(){
  document.querySelector('#quarter')?.addEventListener('change',e=>{const [y,q]=(e.target as HTMLSelectElement).value.split('-').map(Number);currentQuarter=quarterFor(y,q);document.querySelector('#quarter-range')!.textContent=`${prettyDate(currentQuarter.from)} to ${prettyDate(currentQuarter.to)}`;loadRecords();});
  document.querySelector('#add-record')?.addEventListener('click',e=>openDialog('record-dialog',e.currentTarget as HTMLElement));
  document.querySelector('#import-csv')?.addEventListener('click',e=>openDialog('import-dialog',e.currentTarget as HTMLElement));
  document.querySelectorAll<HTMLButtonElement>('.close-dialog').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog')!)));
  document.querySelector('#record-form')?.addEventListener('submit',saveRecord);
  document.querySelector('#csv-file')?.addEventListener('change',readCsv);
  document.querySelector('#confirm-import')?.addEventListener('click',confirmImport);
  document.querySelector('#missing-filter')?.addEventListener('click',e=>{showMissingOnly=!showMissingOnly;(e.currentTarget as HTMLButtonElement).setAttribute('aria-pressed',String(showMissingOnly));(e.currentTarget as HTMLButtonElement).textContent=showMissingOnly?'Show all transactions':'Show missing evidence';renderRecords();});
  document.querySelector('#export-pack')?.addEventListener('click',exportPack);
  document.querySelector('#workspace-settings')?.addEventListener('click',e=>openDialog('settings-dialog',e.currentTarget as HTMLElement));
  document.querySelector('#settings-export')?.addEventListener('click',exportPack);
  document.querySelector('#delete-workspace')?.addEventListener('click',deleteWorkspace);
  document.querySelector('#reset-demo')?.addEventListener('click',async()=>{sessionStorage.removeItem(DEMO_KEY);setNotice('Resetting the demo…');await appPage(true);});
  window.addEventListener('offline',offlineNotice,{once:true});
}
function openDialog(id:string,trigger:HTMLElement){lastTrigger=trigger;const dialog=document.querySelector<HTMLDialogElement>(`#${id}`)!;dialog.showModal();const first=(dialog.querySelector('input,select')||dialog.querySelector('button')) as HTMLElement|null;first?.focus();}
function closeDialog(dialog:HTMLDialogElement){dialog.close();lastTrigger?.focus();}

async function loadRecords(){
  const view=document.querySelector<HTMLDivElement>('#records-view'); if(!view)return; view.className='loading';view.innerHTML='<span>Loading quarter records…</span>';
  try{const response=await api(`/api/workspace?from=${currentQuarter.from}&to=${currentQuarter.to}`);const data=await response.json() as WorkspaceResponse;currentRecords=data.records;renderRecords();}
  catch(error){view.className='';view.innerHTML=`<div class="notice error"><strong>The quarter could not load.</strong><br>${escapeHtml(message(error))} <button class="quiet" type="button" id="retry-load">Try again</button></div>`;document.querySelector('#retry-load')?.addEventListener('click',loadRecords);}
}

function renderRecords(){
  const view=document.querySelector<HTMLDivElement>('#records-view');if(!view)return;
  const visible=showMissingOnly?currentRecords.filter(r=>!r.evidence_name):currentRecords;
  const missing=currentRecords.filter(r=>!r.evidence_name).length;
  const income=currentRecords.filter(r=>r.kind==='income').reduce((n,r)=>n+r.amount_pence,0);
  const expenses=currentRecords.filter(r=>r.kind==='expense').reduce((n,r)=>n+r.amount_pence,0);
  const paid=isPaid();
  let list='';
  if(!visible.length) list=`<div class="empty"><div class="empty-mark" aria-hidden="true"></div><h3>${showMissingOnly?'No missing evidence':'No transactions in this quarter'}</h3><p>${showMissingOnly?'Every transaction has a linked file.':'Add a transaction or import your bank CSV to begin.'}</p>${showMissingOnly?'':'<button class="primary" type="button" id="empty-add">Add the first transaction</button>'}</div>`;
  else list=`<ul class="records">${visible.map(r=>`<li class="record"><time class="record-date" datetime="${r.record_date}">${prettyDate(r.record_date)}</time><div class="record-main"><strong>${escapeHtml(r.description)}</strong><small>${escapeHtml(r.category)} · ${r.source==='bank'?'Bank import':'Added by you'}${r.invoice_number?` · ${escapeHtml(r.invoice_number)}`:''}</small></div><span class="amount ${r.kind}">${r.kind==='income'?'+':'−'}${money(r.amount_pence)}</span><div class="evidence-cell">${r.evidence_name?`<span class="status">Linked</span><span class="file-name" title="${escapeHtml(r.evidence_name)}">${escapeHtml(r.evidence_name)}</span><button class="icon-button remove-evidence" data-id="${r.id}" type="button" aria-label="Remove evidence from ${escapeHtml(r.description)}">×</button>`:`<span class="status missing">Missing</span><label class="quiet" for="evidence-${r.id}">Link file</label><input class="sr-only evidence-input" id="evidence-${r.id}" data-id="${r.id}" type="file" accept="application/pdf,image/jpeg,image/png,image/webp,text/plain">`}</div></li>`).join('')}</ul>`;
  view.className=''; view.innerHTML=`<div class="summary-line" aria-label="Quarter summary"><div class="summary-item"><strong>${currentRecords.length}</strong><span>transactions</span></div><div class="summary-item"><strong>${missing}</strong><span>missing evidence</span></div><div class="summary-item"><strong>${money(income)}</strong><span>income recorded</span></div><div class="summary-item"><strong>${money(expenses)}</strong><span>expenses recorded</span></div></div>${!paid&&currentRecords.length>=25?'<div class="notice"><strong>The free quarter is full.</strong> A monthly subscription allows more than 25 transactions. <a href="/#price">See subscription details</a>.</div>':''}<div class="records-heading"><h2 id="records-title">${showMissingOnly?'Missing evidence':'Quarter transactions'}</h2><span>${visible.length} shown</span></div>${list}`;
  document.querySelectorAll<HTMLButtonElement>('.app-actions button').forEach(button=>button.disabled=false);
  document.querySelector('#empty-add')?.addEventListener('click',e=>openDialog('record-dialog',e.currentTarget as HTMLElement));
  document.querySelectorAll<HTMLInputElement>('.evidence-input').forEach(i=>i.addEventListener('change',linkEvidence));
  document.querySelectorAll<HTMLButtonElement>('.remove-evidence').forEach(b=>b.addEventListener('click',removeEvidence));
}

async function saveRecord(event:Event){
  event.preventDefault(); if(!isPaid()&&currentRecords.length>=25){setFormError('The free quarter has 25 transactions. Restore subscription access or use another quarter.');return;}
  const form=event.currentTarget as HTMLFormElement;const data=new FormData(form);const amount=Number(data.get('amount'));
  if(!Number.isFinite(amount)||amount<=0){setFormError('Enter an amount greater than zero.');return;}
  const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;button.textContent='Saving…';
  try{await api('/api/records',{method:'POST',body:JSON.stringify({kind:data.get('kind'),record_date:data.get('record_date'),description:data.get('description'),amount_pence:Math.round(amount*100),category:data.get('category'),invoice_number:data.get('invoice_number'),source:'manual'})});form.reset();closeDialog(form.closest('dialog')!);setNotice('Transaction saved. Link its evidence when you have it.','success');await loadRecords();}
  catch(error){setFormError(message(error));}finally{button.disabled=false;button.textContent='Save transaction';}
}
function setFormError(text:string){const el=document.querySelector<HTMLDivElement>('#form-error')!;el.hidden=false;el.textContent=text;}

async function linkEvidence(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024){setNotice('The evidence file is over 5 MB. Choose a smaller file.','error');return;}try{const bytes=await file.arrayBuffer();let binary='';new Uint8Array(bytes).forEach(v=>binary+=String.fromCharCode(v));await api(`/api/records/${input.dataset.id}/evidence`,{method:'POST',body:JSON.stringify({name:file.name,mime:file.type||'text/plain',data_base64:btoa(binary)})});setNotice(`${file.name} is linked.`, 'success');await loadRecords();}catch(error){setNotice(message(error),'error');}}
async function removeEvidence(event:Event){const button=event.currentTarget as HTMLButtonElement;const record=currentRecords.find(r=>r.id===button.dataset.id);if(!record||!confirm(`Remove ${record.evidence_name} from ${record.description}?`))return;try{await api(`/api/records/${record.id}/evidence`,{method:'DELETE'});setNotice('Evidence removed. You can link it again.');await loadRecords();}catch(error){setNotice(message(error),'error');}}

type ImportRow={kind:'expense'|'income';record_date:string;description:string;amount_pence:number;category:string;source:'bank';matched:boolean};
let importRows:ImportRow[]=[];
function splitCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows;}
function normaliseDate(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const m=value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:'';}
async function readCsv(event:Event){const file=(event.currentTarget as HTMLInputElement).files?.[0];const review=document.querySelector<HTMLDivElement>('#import-review')!;const confirmButton=document.querySelector<HTMLButtonElement>('#confirm-import')!;confirmButton.hidden=true;if(!file)return;try{const rows=splitCsv(await file.text());const headers=rows.shift()?.map(v=>v.toLowerCase().replace(/[^a-z]/g,''))||[];const dateIndex=headers.findIndex(v=>['date','transactiondate','bookingdate'].includes(v));const descIndex=headers.findIndex(v=>['description','details','memo','narrative'].includes(v));const amountIndex=headers.findIndex(v=>['amount','value','transactionamount'].includes(v));const categoryIndex=headers.findIndex(v=>v==='category');if([dateIndex,descIndex,amountIndex].some(v=>v<0))throw new Error('The CSV needs Date, Description, and Amount columns. Rename those headings and try again.');importRows=rows.map(values=>{const amount=Number((values[amountIndex]||'').replace(/[£, ]/g,''));const date=normaliseDate(values[dateIndex]||'');if(!date||!Number.isFinite(amount)||amount===0||!values[descIndex])return null;const pennies=Math.round(Math.abs(amount)*100);const matched=currentRecords.some(r=>r.record_date===date&&r.amount_pence===pennies);return{kind:amount<0?'expense':'income',record_date:date,description:values[descIndex],amount_pence:pennies,category:values[categoryIndex]||'Uncategorised',source:'bank',matched} as ImportRow;}).filter(Boolean) as ImportRow[];if(!importRows.length)throw new Error('No valid transactions were found. Check the dates and amounts.');const matches=importRows.filter(r=>r.matched).length;review.innerHTML=`<div class="notice ${matches?'':'success'}"><strong>${importRows.length} rows read.</strong> ${matches?`${matches} likely ${matches===1?'match':'matches'} will be skipped.`:'No likely matches found.'}</div><table class="import-table"><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Review</th></tr></thead><tbody>${importRows.slice(0,12).map(r=>`<tr><td>${prettyDate(r.record_date)}</td><td>${escapeHtml(r.description)}</td><td>${r.kind==='expense'?'−':'+'}${money(r.amount_pence)}</td><td>${r.matched?'Likely recorded':'New'}</td></tr>`).join('')}</tbody></table>${importRows.length>12?`<p class="help">Plus ${importRows.length-12} more rows.</p>`:''}`;confirmButton.hidden=false;}catch(error){review.innerHTML=`<div class="notice error">${escapeHtml(message(error))}</div>`;}}
async function confirmImport(){const fresh=importRows.filter(r=>!r.matched);if(!fresh.length){setNotice('Every CSV row already has a likely match.');closeDialog(document.querySelector('#import-dialog')!);return;}if(!isPaid()&&currentRecords.length+fresh.length>25){document.querySelector('#import-review')!.innerHTML='<div class="notice error">This import would pass the free limit of 25 transactions. Use fewer rows or restore subscription access.</div>';return;}const button=document.querySelector<HTMLButtonElement>('#confirm-import')!;button.disabled=true;button.textContent='Importing…';try{await api('/api/records/import',{method:'POST',body:JSON.stringify({records:fresh.map(({matched,...r})=>r)})});closeDialog(document.querySelector('#import-dialog')!);setNotice(`${fresh.length} bank ${fresh.length===1?'transaction':'transactions'} imported.`, 'success');await loadRecords();}catch(error){document.querySelector('#import-review')!.innerHTML=`<div class="notice error">${escapeHtml(message(error))}</div>`;}finally{button.disabled=false;button.textContent='Import new transactions';}}

async function exportPack(){if(!currentRecords.length){setNotice('This quarter has no transactions to export.','error');return;}const button=document.querySelector<HTMLButtonElement>('#export-pack')!;button.disabled=true;button.textContent='Building pack…';try{const response=await api(`/api/export?from=${currentQuarter.from}&to=${currentQuarter.to}`);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`evidence-pack-${currentQuarter.year}-${String(currentQuarter.year+1).slice(-2)}-Q${currentQuarter.q}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Evidence pack downloaded. Review missing rows before sharing.','success');}catch(error){setNotice(message(error),'error');}finally{button.disabled=false;button.textContent='Export evidence pack';}}
async function deleteWorkspace(){const detail=demoMode?'this demo':'your private workspace';if(!confirm(`Delete ${detail} and every file in it? This cannot be undone.`))return;const key=await workspaceKey();try{const response=await fetch('/api/workspace',{method:'DELETE',headers:{'X-Workspace-Key':key,'X-Confirm-Delete':'delete'}});if(!response.ok)throw new Error(await apiError(response));(demoMode?sessionStorage:localStorage).removeItem(demoMode?DEMO_KEY:REAL_KEY);history.pushState({},'','/');await render('/');window.scrollTo(0,0);}catch(error){setNotice(message(error),'error');}}
function setNotice(text:string,type='' as 'success'|'error'|''){const el=document.querySelector<HTMLDivElement>('#app-notice');if(el)el.innerHTML=`<div class="notice ${type}">${escapeHtml(text)}</div>`;}
function offlineNotice(){setNotice('You are offline. Saved records will load again after you reconnect.','');}

function legal(kind:'privacy'|'terms'){
  const privacy=kind==='privacy'; document.title=`${privacy?'Privacy':'Terms'} — MTD Evidence Rail`;
  app.innerHTML=`${header(privacy?'privacy':'')}<main id="main" class="legal"><article class="narrow"><p class="eyebrow">Last updated 29 August 2026</p><h1 tabindex="-1">${privacy?'Your records and privacy':'Terms for using the record aid'}</h1>${privacy?`<p>MTD Evidence Rail stores your transaction records and evidence files on its hosted service. Your browser stores a 64-character workspace key.</p><h2>What we store</h2><p>We store the records, files, and dates that you add.</p><h2>Demo records</h2><p>Demo records use a separate workspace. The demo expires after 24 hours and never reads your private workspace.</p><h2>Who receives data</h2><p>We do not run advertising trackers. Sociobot and Dodo receive checkout details only when you choose the monthly subscription.</p><h2>Retention and deletion</h2><p>The service keeps your private workspace in durable storage. Deleting it removes its records and files.</p><h2>Your choices</h2><p>You can export your records at any time. To request help with deletion, email <a href="mailto:privacy@sociobot.in">privacy@sociobot.in</a>.</p>`:`<p>MTD Evidence Rail helps you organise source records into an evidence pack.</p><h2>Your responsibility</h2><p>Review your records and evidence before sharing them. Keep your workspace key private.</p><h2>Monthly subscription</h2><p>The subscription costs £15 per month and allows more than 25 transactions in a quarter. It renews monthly until you cancel. Sociobot and Dodo handle checkout, cancellation, and refunds.</p><h2>Availability</h2><p>We aim to keep the service available, but we cannot promise uninterrupted access. Export your evidence pack before a deadline.</p><h2>Acceptable use</h2><p>Do not upload unlawful material or try to access another workspace. Files are limited to the supported types and sizes.</p><h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:support@sociobot.in">support@sociobot.in</a>.</p>`}</article></main>${footer()}`;
}
function notFound(){document.title='Page not found — MTD Evidence Rail';app.innerHTML=`${header()}<main id="main" class="not-found"><div class="narrow"><p class="eyebrow">Page not found</p><h1 tabindex="-1">This page was not found</h1><p>The address may have changed. Return to your quarter from the home page.</p><a class="primary" href="/" data-route>Return home</a></div></main>${footer()}`;}

function isPaid(){if(demoMode)return false;const cached=localStorage.getItem(LICENSE_CACHE_KEY);if(!cached)return false;try{const data=JSON.parse(cached);return data.valid===true&&Date.now()-data.checked_at<86_400_000;}catch{return false;}}
function licenseInactive(){if(demoMode)return false;const token=localStorage.getItem(LICENSE_KEY);const cached=localStorage.getItem(LICENSE_CACHE_KEY);if(!token||!cached)return false;try{return JSON.parse(cached).valid===false;}catch{return false;}}
async function verifyLicense(token:string){const response=await fetch(`https://api.sociobot.in/api/v1/products/mtd-evidence-rail/verify?license=${encodeURIComponent(token)}`);if(!response.ok)throw new Error('The subscription check could not finish. Try again.');const data=await response.json();localStorage.setItem(LICENSE_CACHE_KEY,JSON.stringify({...data,checked_at:Date.now()}));return Boolean(data.valid);}
function bindLicenseButtons(){document.querySelectorAll<HTMLButtonElement>('[data-restore-license]').forEach(button=>button.addEventListener('click',async()=>{const input=document.querySelector<HTMLInputElement>(`#${button.dataset.restoreLicense}`)!;const output=document.querySelector<HTMLParagraphElement>('#license-message')!;const token=input.value.trim();if(!token){output.textContent='Paste the subscription token first.';return;}button.disabled=true;output.textContent='Checking the subscription…';try{localStorage.setItem(LICENSE_KEY,token);const valid=await verifyLicense(token);output.textContent=valid?'Subscription access restored.':'This subscription is not active. Check the token or start a subscription.';if(!valid)localStorage.removeItem(LICENSE_KEY);}catch(error){output.textContent=message(error);}finally{button.disabled=false;}}));}
async function captureLicense(){if(isDemoLocation())return;const params=new URLSearchParams(location.search);const token=params.get('license');if(token){localStorage.setItem(LICENSE_KEY,token);params.delete('license');history.replaceState({},'',`${location.pathname}${params.size?`?${params}`:''}${location.hash}`);try{await verifyLicense(token);}catch{/* keep the free first paint */}}const stored=localStorage.getItem(LICENSE_KEY);const cache=localStorage.getItem(LICENSE_CACHE_KEY);if(stored&&(!cache||Date.now()-(JSON.parse(cache).checked_at||0)>86_400_000))verifyLicense(stored).catch(()=>{});}

function message(error:unknown){return error instanceof Error?error.message:'Something went wrong. Try again.';}
async function render(path=location.pathname){showMissingOnly=false;const inDemo=isDemoLocation();if(inDemo)await appPage(true);else {demoMode=false;if(path==='/')landing();else if(path==='/app')await appPage(false);else if(path==='/privacy')legal('privacy');else if(path==='/terms')legal('terms');else notFound();}const canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(canonical)canonical.href=`https://mtd-evidence-rail.sociobot.in${inDemo?'/demo':path==='/'?'':path}`;bindRoutes();routeStatus.textContent=document.title;if(hasRendered)requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}));hasRendered=true;}
function bindRoutes(){document.querySelectorAll<HTMLAnchorElement>('a[data-route]').forEach(link=>link.addEventListener('click',event=>{if(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const url=new URL(link.href);if(url.origin!==location.origin)return;event.preventDefault();history.pushState({},'',url.pathname+url.search+url.hash);render(url.pathname);window.scrollTo(0,0);}));}
window.addEventListener('popstate',()=>render());
captureLicense().finally(()=>render());
